### ISSUE TITLE
app is working but lots of 404

### ISSUE THREAD

**Issue by quenenni** [agorakit/documentation#1]
Hello,

I tried to install Agorakit on a newly configured Debian Buster.
I was able to finish the installation, I can access the first page, but then, every link I click returns a 404.

I think it's simply rewrite rules to put in the webserver vhost (apache in my case), but I have no clue what to put.

Your installation notes doesn't give any pointer on this.

Can I ask you an example of vhost you have?

**Comment by philippejadin** [comment]
I just use the .htaccess file provided by laravel, so maybe you need to enable htaccess file support on your install ?

**Comment by philippejadin** [comment]
btw does it work with `php artisan serve` (using php built-in webserver) ?

**Comment by quenenni** [comment]
Thanks for the quick response.

.htaccess was working.
But I was lacking mod_rewrite and I had an error in the path in the directory statement in my vhost.
Silly me.

Still, thanks for pointing that out. It helped me see my mistakes.

All the links are working. Beautiful. Need to test them now.

But I have still an error with the icon top left of the page, left of the Agorakit.
```
<img src="https://agorakit.xxxxx.yyy/icon/128" width="40" height="40">
```
that returns an error 500.
And I see another error 500 for an icon (GET /icon/192) in the network tab of FF debugger.

No idea why?

**Comment by philippejadin** [comment]
You should check your server logs. I'd guess you need to install GD

**Comment by quenenni** [comment]
Thanks for the tip. 
Indeed it was the package php-gd missing.

I'm going to update the other ticket with the installation procedure.
